#!/usr/bin/env bash
# DriftWatch Tower self-host helper: credential init, stack lifecycle, backup, restore.
#
#   scripts/selfhost.sh init    --env-file FILE [--force]
#   scripts/selfhost.sh up      --env-file FILE [--project NAME] [--build]
#   scripts/selfhost.sh status  --env-file FILE [--project NAME]
#   scripts/selfhost.sh down    --env-file FILE [--project NAME] [--volumes]
#   scripts/selfhost.sh backup  --env-file FILE [--project NAME] --out FILE
#   scripts/selfhost.sh restore --env-file FILE --dump FILE [--project NAME] --target-db NAME
#
# Volumes are never removed unless --volumes is passed explicitly. The script never
# touches containers or volumes it does not own (project name is explicit).

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

COMMAND="${1:-}"; shift || true
ENV_FILE=".execution/selfhost.env"
PROJECT="driftwatch"
BUILD_FLAG=""
REMOVE_VOLUMES=0
OUT_FILE=""
DUMP_FILE=""
TARGET_DB=""

usage() {
  sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --env-file) ENV_FILE="$2"; shift 2 ;;
    --project)  PROJECT="$2"; shift 2 ;;
    --out)      OUT_FILE="$2"; shift 2 ;;
    --dump)     DUMP_FILE="$2"; shift 2 ;;
    --target-db) TARGET_DB="$2"; shift 2 ;;
    --build)    BUILD_FLAG="--build"; shift ;;
    --volumes)  REMOVE_VOLUMES=1; shift ;;
    --help|-h)  usage ;;
    *) die "unknown argument: $1" ;;
  esac
done

compose() {
  docker compose -p "$PROJECT" --env-file "$ENV_FILE" "$@"
}

generate_secret() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 32; }

cmd_init() {
  if [ -f "$ENV_FILE" ]; then
    log "env file already exists: $ENV_FILE (leaving it untouched)"
    exit 0
  fi
  mkdir -p "$(dirname "$ENV_FILE")"
  local pg_password admin_password ingest_token
  pg_password="$(generate_secret)"
  admin_password="$(generate_secret)"
  ingest_token="$(generate_secret)$(generate_secret)"
  (umask 077; cat > "$ENV_FILE" <<EOF
# Generated by scripts/selfhost.sh init on $(utc_now). Never commit this file.
DWT_POSTGRES_DB=driftwatch
DWT_POSTGRES_USER=driftwatch
DWT_POSTGRES_PASSWORD=$pg_password
DWT_ADMIN_USERNAME=driftwatch
DWT_ADMIN_PASSWORD=$admin_password
DWT_INGEST_TOKEN=$ingest_token
# 18080 keeps acceptance runs off the common 8080; a self-host install can use 8080.
DWT_APP_PORT=${DWT_APP_PORT:-18080}
DWT_SPRING_PROFILES=selfhost
EOF
  )
  chmod 600 "$ENV_FILE"
  log "wrote $ENV_FILE (0600) with fresh random credentials"
}

cmd_up() {
  load_env_file "$ENV_FILE"
  require_docker
  compose up -d $BUILD_FLAG
  local port="${DWT_APP_PORT:-8080}"
  wait_http "http://127.0.0.1:${port}/actuator/health/readiness" 180 200 \
    || die "application did not become ready on 127.0.0.1:${port} within 180s"
  log "stack is ready on 127.0.0.1:${port}"
}

cmd_status() {
  load_env_file "$ENV_FILE"
  require_docker
  compose ps
  local port="${DWT_APP_PORT:-8080}"
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:${port}/actuator/health/readiness" || true)"
  echo "readiness HTTP ${code:-000} on 127.0.0.1:${port}"
  [ "$code" = "200" ] || exit 1
}

cmd_down() {
  load_env_file "$ENV_FILE"
  require_docker
  if [ "$REMOVE_VOLUMES" = "1" ]; then
    log "removing project '$PROJECT' including its volumes"
    compose down -v
  else
    log "stopping project '$PROJECT' (volumes kept; pass --volumes to remove them)"
    compose down
  fi
}

cmd_backup() {
  [ -n "$OUT_FILE" ] || die "backup requires --out FILE"
  load_env_file "$ENV_FILE"
  require_docker
  mkdir -p "$(dirname "$OUT_FILE")"
  compose exec -T postgres pg_dump -U "$DWT_POSTGRES_USER" -d "$DWT_POSTGRES_DB" -Fc > "$OUT_FILE"
  log "wrote custom-format dump to $OUT_FILE ($(wc -c < "$OUT_FILE") bytes)"
}

cmd_restore() {
  [ -n "$DUMP_FILE" ] || die "restore requires --dump FILE"
  [ -f "$DUMP_FILE" ] || die "dump not found: $DUMP_FILE"
  [ -n "$TARGET_DB" ] || die "restore requires --target-db NAME (the dump is restored into a new database, never over an existing one)"
  load_env_file "$ENV_FILE"
  require_docker
  compose exec -T postgres psql -U "$DWT_POSTGRES_USER" -d postgres \
    -c "CREATE DATABASE ${TARGET_DB};"
  compose exec -T postgres pg_restore -U "$DWT_POSTGRES_USER" -d "$TARGET_DB" --no-owner < "$DUMP_FILE"
  log "restored $DUMP_FILE into database $TARGET_DB"
}

case "$COMMAND" in
  init)    cmd_init ;;
  up)      cmd_up ;;
  status)  cmd_status ;;
  down)    cmd_down ;;
  backup)  cmd_backup ;;
  restore) cmd_restore ;;
  *)       usage ;;
esac